project:
  type: website

website:
  title: "mbeynaerts.github.io"
  navbar:
    background: "#20364c"
    foreground: "#ffffff"
    right:
      - href: index.qmd
        text: About
      - research.qmd
      - teaching.qmd
      - vitae.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

